
kafka:
  bootstrap-servers: localhost:9092
  group:
    id: test-consumer-group
  topic:
    poc: poc

rabbit:
  queueName: poc
  exchangeName: poce
server:
  port: 0

spammer:
  numOfMessages: 250000
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.102.159
          zk-nodes: 192.168.102.159

