
kafka:
  bootstrap-servers: 10.0.2.2:9092
  group:
    id: test-consumer-group
  topic:
    poc: poc

rabbit:
  queueName: poc
  exchangeName: poce
server:
  port: 0

spammer:
  numOfMessages: 250000
spring:
  rabbitmq:
    host: 10.0.2.2
  kafka:
    producer:
      bootstrap-servers: 10.0.2.2:9092
