
kafka:
  bootstrap-servers: 127.0.0.1:9092
  group:
    id: test-consumer-group
  topic:
    poc: poc

rabbit:
  queueName: poc
  exchangeName: poce
server:
  port: 0

spammer:
  numOfMessages: 100
spring:
  rabbitmq:
    host: 127.0.0.1
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
